### ISSUE TITLE
Broken social media link for team member

### ISSUE THREAD

**Issue by HassanBahati** [oscakampala/oscakampala.github.io#40]
Social media link for linkedin returns 404 when clicked
![Screenshot from 2022-08-28 23-39-37](https://user-images.githubusercontent.com/65954740/187093621-4ea43f0c-0753-4818-875b-7af5299e8b99.png)

![Screenshot from 2022-08-28 23-37-38](https://user-images.githubusercontent.com/65954740/187093583-d3dfd8b7-f1e2-46b0-b22a-196b075ea2ed.png)

**Comment by SyfaCollins** [comment]
They all working

**Comment by HassanBahati** [comment]
@SyfaCollins they were fixed via #41.

**Comment by HassanBahati** [comment]
Closing this issue as it as fixed via #41
