### ISSUE TITLE
Footer coverage

### ISSUE THREAD

**Issue by HassanBahati** [oscakampala/oscakampala.github.io#47]
The footer seems to be convering less than full-width of the page. this is as seem from the [home page](https://oscakampala.org/)
![Screenshot from 2023-01-06 12-23-49](https://user-images.githubusercontent.com/65954740/210971441-7a2a875c-b284-464a-8ae1-a95ece812669.png)

Wouldnt it be better taking full page width??

@SyfaCollins could this be how it was intended in the design?

**Comment by SyfaCollins** [comment]
Yes @HassanBahati  that is how it was intended to be its also reflected on the Teams sections they all got the same sides margins

**Comment by HassanBahati** [comment]
Okay then, thanks for the clarification @SyfaCollins
