### ISSUE TITLE
This part links to the wrong issues 

### ISSUE THREAD

**Issue by KakoozaJerry** [oscakampala/oscakampala.github.io#7]
https://github.com/oscakampala/oscakampala.github.io/blob/9479036a8864745bf0b6e10101dc5d7d68aaf481/README.md?plain=1#L34

@Samsonroyal , we need to make these parts link to this repository issues tab and not tts

**Comment by KakoozaJerry** [comment]
Same for this https://github.com/oscakampala/oscakampala.github.io/blob/9479036a8864745bf0b6e10101dc5d7d68aaf481/README.md?plain=1#L41 and below

**Comment by KakoozaJerry** [comment]
I suggest that the documentation link is left out

**Comment by Samsonroyal** [comment]
Let me work on these too; as my adrenaline is still high from that PR merge
😂 🤣
